export enum ContactMethod{
    EMAIL = 'EMAIL',
    PHONE = 'PHONE',
    WHATSAPP = 'WHATSAPP',
    WECHAT = 'WECHAT',
    FACEBOOK = 'FACEBOOK',
    LINKEDIN = 'LINKEDIN',
    INSTAGRAM = 'INSTAGRAM',
    TWITTER = 'TWITTER',
    WEBSITE = 'WEBSITE',
    IN_PERSON = 'IN_PERSON',
    OTHER = 'OTHER'
}